# Generated by Django 4.2.1 on 2023-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorageDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field_name', models.FileField(storage='customstorage.CustomStorage()', upload_to='')),
            ],
        ),
    ]
