# Generated by Django 4.2.1 on 2023-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestoragedb',
            name='file_field_name',
            field=models.FileField(storage='customstorage.CustomStorage', upload_to=''),
        ),
    ]
