# Generated by Django 4.2.1 on 2023-06-10 13:32

import customstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customstorage', '0002_alter_filestoragedb_file_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestoragedb',
            name='file_field_name',
            field=models.FileField(storage=customstorage.storage.CustomStorage(), upload_to=''),
        ),
    ]
