# Generated by Django 4.2.2 on 2023-07-25 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentListing',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Department Listing',
                'verbose_name_plural': 'Department Listings',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Faculty Listing',
                'verbose_name_plural': 'Faculty Listing',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=250, null=True, verbose_name='course code')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='course title')),
                ('unit', models.IntegerField(default=1, null=True, verbose_name='credit unit')),
            ],
            options={
                'verbose_name': 'Course listing',
                'verbose_name_plural': 'Course Listing',
            },
        ),
        migrations.CreateModel(
            name='RegisterStudentSubject',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=250, null=True, verbose_name='course code')),
                ('unit', models.IntegerField(default=1, editable=False, null=True, verbose_name='credit unit')),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester')], default='first', max_length=500, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to='dashboard.departmentlisting')),
                ('levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_course_level_rel', to='dashboard.levels')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='dashboard.subjects', verbose_name='Courses')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='authuser.studentmodel', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Student Course',
                'verbose_name_plural': 'Student Courses',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.departmentlisting')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authuser.studentmodel')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='departmentlisting',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_listing_faculty_rel', to='dashboard.faculty'),
        ),
        migrations.CreateModel(
            name='CreateAttendance',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=500, null=True, unique=True)),
                ('attributes', models.CharField(help_text='month/day/month_name', max_length=50, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('retake', 'retake')], default='pending', max_length=250)),
                ('total_number_students', models.IntegerField(default=0)),
                ('time_elapsed', models.IntegerField(default=0)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_related', to='dashboard.departmentlisting')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_related', to='authuser.lecturermodel')),
                ('levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_rel', to='dashboard.levels')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_related', to='dashboard.subjects', verbose_name='Courses')),
            ],
            options={
                'verbose_name': 'Create Attendance',
                'verbose_name_plural': 'Create Attendance',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester')], default='first', max_length=500, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_courses', to='dashboard.departmentlisting')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_courses', to='authuser.lecturermodel')),
                ('levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_level_rel', to='dashboard.levels')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_courses', to='dashboard.subjects', verbose_name='Courses')),
            ],
            options={
                'verbose_name': 'Lecturer Course',
                'verbose_name_plural': 'Lecturer Courses',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('start', 'Started'), ('end', 'Ended'), ('retake', 'Retake')], max_length=50, null=True)),
                ('attendance_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('attendance_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_attendance_rel', to='dashboard.createattendance')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_department_related', to='dashboard.departmentlisting')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lecturer_related', to='authuser.lecturermodel')),
                ('levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_level_rel', to='dashboard.levels')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taken_student', to='authuser.studentmodel')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_subject_related', to='dashboard.subjects')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'View Attendances',
            },
        ),
    ]
