# Generated by Django 4.2.2 on 2023-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createattendance',
            name='time_elapsed',
            field=models.IntegerField(default=5),
        ),
    ]
