# Generated by Django 4.2.2 on 2023-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_createattendance_time_elapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='createattendance',
            name='time_elapsed2',
            field=models.IntegerField(default=5),
        ),
    ]
