# Generated by Django 4.2.2 on 2023-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('title', models.CharField(max_length=150, null=True)),
                ('subtitle', models.CharField(max_length=150, null=True)),
                ('content', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('title', models.CharField(max_length=150, null=True)),
                ('subtitle', models.CharField(max_length=150, null=True)),
                ('content', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('title', models.CharField(max_length=150, null=True)),
                ('subtitle', models.CharField(max_length=150, null=True)),
                ('content', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
