# Generated by Django 4.2.2 on 2023-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_studentmodel_gender_studentmodel_stateoforigin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='stateOfOrigin',
            new_name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
