# Generated by Django 4.2.2 on 2023-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_studentmodel_address_studentmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=150, null=True),
        ),
    ]
