# Generated by Django 4.2.2 on 2023-08-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_remove_studentmodel_age_studentmodel_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='dob',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
