# Generated by Django 4.2.2 on 2023-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_alter_studentmodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=250, null=True),
        ),
    ]
