# Generated by Django 4.2.2 on 2023-08-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0011_user_account_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type2',
        ),
    ]
